// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Float64.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _Float64_H_
#define _Float64_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

/*!
 * @brief This struct represents the structure Float64 defined by the user in the IDL file.
 * @ingroup FLOAT64
 */
typedef struct Float64
{
    double data;
} Float64;

struct ucdrBuffer;

bool Float64_serialize_topic(struct ucdrBuffer* writer, const Float64* topic);
bool Float64_deserialize_topic(struct ucdrBuffer* reader, Float64* topic);
uint32_t Float64_size_of_topic(const Float64* topic, uint32_t size);


#ifdef __cplusplus
}
#endif

#endif // _Float64_H_