#include "Header.idl"

struct JointState
{
    Header header;
    octet name[10][32];
    unsigned long name_size;
    double position[10];
    unsigned long position_size;
    double velocity[10];
    unsigned long velocity_size;
    double effort[10];
    unsigned long effort_size;
};
